<?php /* Smarty version Smarty-3.1.15, created on 2015-01-11 22:22:33
         compiled from "D:\wamp\www\iyouwu\themes\web\admin\account\account_view.html" */ ?>
<?php /*%%SmartyHeaderCode:784954b0d459c41342-67755573%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '23ee92b389734f13752e985f2651634045bb6b11' => 
    array (
      0 => 'D:\\wamp\\www\\iyouwu\\themes\\web\\admin\\account\\account_view.html',
      1 => 1420967191,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '784954b0d459c41342-67755573',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.15',
  'unifunc' => 'content_54b0d459c9b0d3_74100362',
  'variables' => 
  array (
    'account' => 0,
    'app_http_url' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_54b0d459c9b0d3_74100362')) {function content_54b0d459c9b0d3_74100362($_smarty_tpl) {?><!DOCTYPE html><!--[if IE 8]><html lang="en" class="ie8"> <![endif]--><!--[if IE 9]><html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en"> <!--<![endif]--><!-- BEGIN HEAD --><head>    <meta charset="utf-8"/>    <title>尤物后台管理系统-管理员信息</title>    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    <meta content="" name="description"/>    <meta content="" name="author"/>    <!-- BEGIN GLOBAL MANDATORY STYLES -->    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-metro.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-responsive.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/uniform.default.css" rel="stylesheet" type="text/css"/>    <!-- END GLOBAL MANDATORY STYLES -->    <!-- BEGIN PAGE LEVEL STYLES -->    <link rel="stylesheet" type="text/css" href="../../../../statics/resource/common/plugs/metronic/css/select2_metro.css"/>    <!-- END PAGE LEVEL SCRIPTS -->    <link rel="shortcut icon" href="../../../../statics/resource/common/plugs/metronic/image/favicon.ico"/></head><!-- END HEAD --><!-- BEGIN BODY --><body class="page-header-fixed" style="background-color:#FFFFFF !important"><div class="tab-pane margin-top-10">    <div class="portlet box blue">        <div class="portlet-title">            <div class="caption"><i class="icon-reorder"></i>管理员信息</div>            <div class="tools">                <a href="javascript:;" class="collapse"></a>            </div>        </div>        <div class="portlet-body form">            <!-- BEGIN FORM-->            <div class="form-horizontal form-view">                <h3 class="form-section">必填信息</h3>                <div class="row-fluid">                    <div class="span6 ">                        <div class="control-group">                            <label class="control-label">账户:</label>                            <div class="controls">                                <span class="text"><?php echo $_smarty_tpl->tpl_vars['account']->value['UserName'];?>
</span>                            </div>                        </div>                    </div>                    <!--/span-->                    <div class="span6 ">                        <div class="control-group">                            <label class="control-label">真实姓名:</label>                            <div class="controls">                                <span class="text"><?php echo $_smarty_tpl->tpl_vars['account']->value['RealName'];?>
</span>                            </div>                        </div>                    </div>                    <!--/span-->                </div>                <h3 class="form-section">选填信息</h3>                <div class="row-fluid">                    <?php if ($_smarty_tpl->tpl_vars['account']->value['Email']) {?>                    <div class="span6 ">                        <div class="control-group">                            <label class="control-label">公司邮箱:</label>                            <div class="controls">                                <span class="text"><?php echo $_smarty_tpl->tpl_vars['account']->value['Email'];?>
</span>                            </div>                        </div>                    </div>                    <?php }?>                    <?php if ($_smarty_tpl->tpl_vars['account']->value['QQ']) {?>                    <div class="span6">                        <div class="control-group">                            <label class="control-label">企业QQ:</label>                            <div class="controls">                                <span class="text"><?php echo $_smarty_tpl->tpl_vars['account']->value['QQ'];?>
</span>                            </div>                        </div>                    </div>                    <?php }?>                </div>                <div class="row-fluid">                    <?php if ($_smarty_tpl->tpl_vars['account']->value['Phone']) {?>                    <div class="span6 ">                        <div class="control-group">                            <label class="control-label">分机:</label>                            <div class="controls">                                <span class="text"><?php echo $_smarty_tpl->tpl_vars['account']->value['Phone'];?>
</span>                            </div>                        </div>                    </div>                    <?php }?>                    <?php if ($_smarty_tpl->tpl_vars['account']->value['Mobile']) {?>                    <div class="span6">                        <div class="control-group">                            <label class="control-label">手机:</label>                            <div class="controls">                                <span class="text"><?php echo $_smarty_tpl->tpl_vars['account']->value['Mobile'];?>
</span>                            </div>                        </div>                    </div>                    <?php }?>                </div>                <div class="form-actions text-center">                    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Account/EditAccount?account_id=<?php echo $_smarty_tpl->tpl_vars['account']->value['ID'];?>
"><button type="submit" class="btn blue"><i class="icon-pencil"></i>修改</button></a>                    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Account/ListAccount"><button class="btn" type="button">返回</button></a>                </div>            </div>            <!-- END FORM-->        </div>    </div></div><!-- END FOOTER --><!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) --><!-- BEGIN CORE PLUGINS --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-1.10.1.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script><!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/bootstrap.min.js" type="text/javascript"></script><!--[if lt IE 9]><script src="../../../../statics/resource/common/plugs/metronic/js/excanvas.min.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/respond.min.js"></script><![endif]--><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.slimscroll.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.blockui.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.cookie.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.uniform.min.js" type="text/javascript"></script><!-- END CORE PLUGINS --><!-- BEGIN PAGE LEVEL PLUGINS --><script type="text/javascript" src="../../../../statics/resource/common/plugs/metronic/js/select2.min.js"></script><!-- END PAGE LEVEL PLUGINS --><!-- BEGIN PAGE LEVEL SCRIPTS --><script src="../../../../statics/resource/common/plugs/metronic/js/app.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/form-samples.js"></script><!-- END PAGE LEVEL SCRIPTS --><script>    jQuery(document).ready(function () {        // initiate layout and plugins        App.init();        FormSamples.init();    });</script><!-- END JAVASCRIPTS --></body><!-- END BODY --></html><?php }} ?>
