<?php /* Smarty version Smarty-3.1.15, created on 2015-02-02 18:27:22
         compiled from "D:\wamp\www\iyouwu\themes\web\admin\goods\goods_view.html" */ ?>
<?php /*%%SmartyHeaderCode:1490754c74548594bd4-35583887%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '3d823967902fd1700a960bc0970c3329cd6fd292' => 
    array (
      0 => 'D:\\wamp\\www\\iyouwu\\themes\\web\\admin\\goods\\goods_view.html',
      1 => 1422716293,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '1490754c74548594bd4-35583887',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.15',
  'unifunc' => 'content_54c74548b88431_62532427',
  'variables' => 
  array (
    'goods' => 0,
    'app_http_url' => 0,
    'goods_picture' => 0,
    'picture' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_54c74548b88431_62532427')) {function content_54c74548b88431_62532427($_smarty_tpl) {?><!DOCTYPE html><!--[if IE 8]><html lang="en" class="ie8"> <![endif]--><!--[if IE 9]><html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en"> <!--<![endif]--><!-- BEGIN HEAD --><head>    <meta charset="utf-8"/>    <title>尤物后台管理系统-商品图片信息</title>    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    <meta content="" name="description"/>    <meta content="" name="author"/>    <!-- BEGIN GLOBAL MANDATORY STYLES -->    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-metro.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-responsive.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/uniform.default.css" rel="stylesheet" type="text/css"/>    <!-- END GLOBAL MANDATORY STYLES -->    <!-- BEGIN PAGE LEVEL STYLES -->    <link rel="stylesheet" type="text/css" href="../../../../statics/resource/common/plugs/metronic/css/select2_metro.css"/>    <!-- END PAGE LEVEL SCRIPTS -->    <link rel="shortcut icon" href="../../../../statics/resource/common/plugs/metronic/image/favicon.ico"/></head><!-- END HEAD --><!-- BEGIN BODY --><body class="page-header-fixed" style="background-color:#FFFFFF !important"><div class="tab-pane margin-top-10"><div class="portlet box blue"><div class="portlet-title">    <div class="caption"><i class="icon-reorder"></i><?php echo $_smarty_tpl->tpl_vars['goods']->value['NameCn'];?>
商品信息查看</div>    <div class="tools">        <a href="javascript:;" class="collapse"></a>    </div></div><div class="portlet-body form"><!-- BEGIN FORM--><div class="form-horizontal form-view"><h3 class="form-section">    <?php echo $_smarty_tpl->tpl_vars['goods']->value['NameCn'];?>
基本信息：    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Goods/ListGoods"><button class="btn green" style="float: right">返回列表</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Goods/PictureGoods?goods_id=<?php echo $_smarty_tpl->tpl_vars['goods']->value['ID'];?>
"><button class="btn blue" style="float: right"><i class="icon-pencil"></i>编辑图片</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Goods/EditGoods?goods_id=<?php echo $_smarty_tpl->tpl_vars['goods']->value['ID'];?>
"><button class="btn red" style="float: right"><i class="icon-pencil"></i>编辑商品</button></a></h3><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品唯一编号:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['GoodsCode'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品中文名称:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['NameCn'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品英文名称:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['NameEn'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品拼音:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['NamePinYin'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品品牌:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['BrandId'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品所属分类:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['CategoryId'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品目标群体:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['GroupId'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">商品供应商:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['GoodsAgentId'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">采购价:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['BuyPrice'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">销售价:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['SalePrice'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">市场价:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['MarketPrice'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">币种:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['MoneyType'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">促销开始日期:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['PromotionStartDate'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">促销结束日期:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['PromotionEndDate'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">促销价:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['PromotionPrice'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">是否促销:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods']->value['Promotion']==0) {?>否<?php } else { ?>是<?php }?></span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">是否热销:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods']->value['Hot']==0) {?>否<?php } else { ?>是<?php }?></span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">是否上架:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods']->value['Valid']==0) {?>否<?php } else { ?>是<?php }?></span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">配送价格:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['DeliveryPrice'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">是否配送:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods']->value['Delivery']==0) {?>否<?php } else { ?>是<?php }?></span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span12 ">        <div class="control-group">            <label class="control-label">商品简介:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['Introduction'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span12 ">        <div class="control-group">            <label class="control-label">商品详细信息:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['Detail'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span12 ">        <div class="control-group">            <label class="control-label">备注:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods']->value['Notice'];?>
</span>            </div>        </div>    </div></div>    <h3 class="form-section"><?php echo $_smarty_tpl->tpl_vars['goods']->value['NameCn'];?>
图片信息：</h3>    <div class="row-fluid">        <div class="span12 ">            <div class="control-group">                <?php if ($_smarty_tpl->tpl_vars['goods_picture']->value) {?>                <?php  $_smarty_tpl->tpl_vars['picture'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['picture']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['goods_picture']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['picture']->key => $_smarty_tpl->tpl_vars['picture']->value) {
$_smarty_tpl->tpl_vars['picture']->_loop = true;
?>                    <img src="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
<?php echo $_smarty_tpl->tpl_vars['picture']->value['PictureSrc'];?>
" width="180" height="200">                <?php } ?>                <?php } else { ?>                暂无该商品的图片信息                <?php }?>            </div>        </div>    </div><div class="form-actions text-right">    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Goods/EditGoods?goods_id=<?php echo $_smarty_tpl->tpl_vars['goods']->value['ID'];?>
"><button class="btn red"><i class="icon-pencil"></i>编辑商品</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Goods/PictureGoods?goods_id=<?php echo $_smarty_tpl->tpl_vars['goods']->value['ID'];?>
"><button class="btn blue"><i class="icon-pencil"></i>编辑图片</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
Goods/ListGoods"><button class="btn green">返回列表</button></a></div></div><!-- END FORM--></div></div></div><!-- END FOOTER --><!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) --><!-- BEGIN CORE PLUGINS --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-1.10.1.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script><!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/bootstrap.min.js" type="text/javascript"></script><!--[if lt IE 9]><script src="../../../../statics/resource/common/plugs/metronic/js/excanvas.min.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/respond.min.js"></script><![endif]--><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.slimscroll.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.blockui.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.cookie.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.uniform.min.js" type="text/javascript"></script><!-- END CORE PLUGINS --><!-- BEGIN PAGE LEVEL PLUGINS --><script type="text/javascript" src="../../../../statics/resource/common/plugs/metronic/js/select2.min.js"></script><!-- END PAGE LEVEL PLUGINS --><!-- BEGIN PAGE LEVEL SCRIPTS --><script src="../../../../statics/resource/common/plugs/metronic/js/app.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/form-samples.js"></script><!-- END PAGE LEVEL SCRIPTS --><script>    jQuery(document).ready(function () {        // initiate layout and plugins        App.init();        FormSamples.init();    });</script><!-- END JAVASCRIPTS --></body><!-- END BODY --></html><?php }} ?>
