<?php /* Smarty version Smarty-3.1.15, created on 2016-01-02 00:55:51
         compiled from "/data/home/byu17691/htdocs/themes/web/admin/goods_base/category_add.html" */ ?>
<?php /*%%SmartyHeaderCode:632301655686af970b2990-33748824%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '4916ab938e78f23d224af84449e1ca7960f75fcc' => 
    array (
      0 => '/data/home/byu17691/htdocs/themes/web/admin/goods_base/category_add.html',
      1 => 1420998330,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '632301655686af970b2990-33748824',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'app_http_url' => 0,
    'category' => 0,
    'first_category' => 0,
    'first_category_item' => 0,
    'save_error' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.15',
  'unifunc' => 'content_5686af97129014_01344903',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_5686af97129014_01344903')) {function content_5686af97129014_01344903($_smarty_tpl) {?><!DOCTYPE html><!--[if IE 8]><html lang="en" class="ie8"> <![endif]--><!--[if IE 9]><html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en"> <!--<![endif]--><!-- BEGIN HEAD --><head>    <meta charset="utf-8"/>    <title>尤物后台管理系统-新增商品类型</title>    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    <meta content="" name="description"/>    <meta content="" name="author"/>    <!-- BEGIN GLOBAL MANDATORY STYLES -->    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-metro.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-responsive.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/uniform.default.css" rel="stylesheet" type="text/css"/>    <!-- END GLOBAL MANDATORY STYLES -->    <!-- BEGIN PAGE LEVEL STYLES -->    <link rel="stylesheet" type="text/css" href="../../../../statics/resource/common/plugs/metronic/css/select2_metro.css"/>    <!-- END PAGE LEVEL SCRIPTS -->    <link rel="shortcut icon" href="../../../../statics/resource/common/plugs/metronic/image/favicon.ico"/></head><!-- END HEAD --><!-- BEGIN BODY --><body class="page-header-fixed" style="background-color:#FFFFFF !important"><div class="tab-pane  margin-top-10">    <div class="portlet box green">        <div class="portlet-title">            <div class="caption"><i class="icon-reorder"></i>新增商品类型</div>            <div class="tools">                <a href="javascript:;" class="collapse"></a>            </div>        </div>        <div class="portlet-body form">            <!-- BEGIN FORM-->            <form action="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsBase/AddGoodsCategory" method="post" onSubmit="return chkinput(this)" class="form-horizontal">                <h3 class="form-section">商品类型：</h3>                <div class="row-fluid">                    <div class="span4 ">                        <div class="control-group">                            <label class="control-label">类型名称 *：</label>                            <div class="controls">                                <input name="CategoryName" type="text" maxlength="20" value="<?php echo $_smarty_tpl->tpl_vars['category']->value['CategoryName'];?>
" class="m-wrap span12" placeholder="">                            </div>                        </div>                    </div>                    <div class="span4 ">                        <div class="control-group">                            <label class="control-label">所属类型：</label>                            <div class="controls">                                <select name="ParentId">                                    <option value="0">--请选择所属类型--</option>                                    <?php  $_smarty_tpl->tpl_vars['first_category_item'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['first_category_item']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['first_category']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['first_category_item']->key => $_smarty_tpl->tpl_vars['first_category_item']->value) {
$_smarty_tpl->tpl_vars['first_category_item']->_loop = true;
?>                                        <option value="<?php echo $_smarty_tpl->tpl_vars['first_category_item']->value['ID'];?>
"><?php echo $_smarty_tpl->tpl_vars['first_category_item']->value['CategoryName'];?>
</option>                                    <?php } ?>                                </select>                            </div>                        </div>                    </div>                    <div class="span4 ">                        <div class="control-group">                            <label class="control-label">是否有效：</label>                            <div class="controls">                                <label class="radio">                                    <div class="radio">                                        <input value="0" name="Valid" type="radio">                                    </div>                                    否                                </label>                                <label class="radio">                                    <div class="radio">                                        <input value="1" name="Valid" type="radio" checked="checked">                                    </div>                                    是                                </label>                            </div>                        </div>                    </div>                </div>                <div class="form-actions text-center">                    <button type="submit" class="btn blue"><i class="icon-ok"></i> 保存</button>                    <button type="button" id="category_list_bak" class="btn">返回</button>                </div>            </form>            <!-- END FORM-->        </div>    </div></div><input type="hidden" id="save_error" value="<?php echo $_smarty_tpl->tpl_vars['save_error']->value;?>
" /><input type="hidden" id="app_http_url" name="app_http_url"  value="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
"/><input type="hidden" id="category_list" value="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsBase/ListGoodsCategory" /><!-- END FOOTER --><!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) --><!-- BEGIN CORE PLUGINS --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-1.10.1.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script><!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/bootstrap.min.js" type="text/javascript"></script><!--[if lt IE 9]><script src="../../../../statics/resource/common/plugs/metronic/js/excanvas.min.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/respond.min.js"></script><![endif]--><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.slimscroll.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.blockui.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.cookie.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.uniform.min.js" type="text/javascript"></script><!-- END CORE PLUGINS --><!-- BEGIN PAGE LEVEL PLUGINS --><script type="text/javascript" src="../../../../statics/resource/common/plugs/metronic/js/select2.min.js"></script><!-- END PAGE LEVEL PLUGINS --><!-- BEGIN PAGE LEVEL SCRIPTS --><script src="../../../../statics/resource/common/plugs/metronic/js/app.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/form-samples.js"></script><!-- END PAGE LEVEL SCRIPTS --><script>    jQuery(document).ready(function () {        // initiate layout and plugins        App.init();        FormSamples.init();    });    var app_http_url = $("#app_http_url").val();    $(document).ready(function () {        if ($("#save_error").val()) { //保存失败提示            alert("保存失败!");        }        $("#category_list_bak").click(function () { //返回按钮            window.location.href = $("#category_list").val();        });    });    //form表单验证    function chkinput(form) {        if ($.trim(form.CategoryName.value) == "") {            alert("请输入商品类型!");            form.CategoryName.select();            return(false);        }        return true;    }</script><!-- END JAVASCRIPTS --></body><!-- END BODY --></html><?php }} ?>
