<?php /* Smarty version Smarty-3.1.15, created on 2015-01-27 22:00:55
         compiled from "D:\wamp\www\iyouwu\themes\web\admin\travel_supplier\travel_supplier_view.html" */ ?>
<?php /*%%SmartyHeaderCode:900954c78a620e89d3-44771282%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '72046454e38050ffdb4a592b6e406e32630eb916' => 
    array (
      0 => 'D:\\wamp\\www\\iyouwu\\themes\\web\\admin\\travel_supplier\\travel_supplier_view.html',
      1 => 1422367194,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '900954c78a620e89d3-44771282',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.15',
  'unifunc' => 'content_54c78a622b5941_21408906',
  'variables' => 
  array (
    'travel_supplier' => 0,
    'app_http_url' => 0,
    'travel_supplier_file' => 0,
    'file' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_54c78a622b5941_21408906')) {function content_54c78a622b5941_21408906($_smarty_tpl) {?><!DOCTYPE html><!--[if IE 8]><html lang="en" class="ie8"> <![endif]--><!--[if IE 9]><html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en"> <!--<![endif]--><!-- BEGIN HEAD --><head>    <meta charset="utf-8"/>    <title>尤物后台管理系统-旅游供应商信息</title>    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    <meta content="" name="description"/>    <meta content="" name="author"/>    <!-- BEGIN GLOBAL MANDATORY STYLES -->    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-metro.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-responsive.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/uniform.default.css" rel="stylesheet" type="text/css"/>    <!-- END GLOBAL MANDATORY STYLES -->    <!-- BEGIN PAGE LEVEL STYLES -->    <link rel="stylesheet" type="text/css" href="../../../../statics/resource/common/plugs/metronic/css/select2_metro.css"/>    <!-- END PAGE LEVEL SCRIPTS -->    <link rel="shortcut icon" href="../../../../statics/resource/common/plugs/metronic/image/favicon.ico"/></head><!-- END HEAD --><!-- BEGIN BODY --><body class="page-header-fixed" style="background-color:#FFFFFF !important"><div class="tab-pane margin-top-10"><div class="portlet box blue"><div class="portlet-title">    <div class="caption"><i class="icon-reorder"></i><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['NameCn'];?>
旅游供应商信息查看</div>    <div class="tools">        <a href="javascript:;" class="collapse"></a>    </div></div><div class="portlet-body form"><!-- BEGIN FORM--><div class="form-horizontal form-view"><h3 class="form-section">    <?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['NameCn'];?>
基本信息：    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
TravelSupplier/ListTravelSupplier"><button class="btn green" style="float: right">返回列表</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
TravelSupplier/FileTravelSupplier?travel_supplier_id=<?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['ID'];?>
"><button class="btn blue" style="float: right"><i class="icon-pencil"></i>编辑文件</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
TravelSupplier/EditTravelSupplier?travel_supplier_id=<?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['ID'];?>
"><button class="btn red" style="float: right"><i class="icon-pencil"></i>编辑旅游供应商</button></a></h3><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">旅游供应商名称:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['Name'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">佣金比例:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['Commission'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">是否有效:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['travel_supplier']->value['Valid']==1) {?>是<?php } else { ?>否<?php }?></span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">合作时限:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['StartDate'];?>
-<?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['EndDate'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6">        <div class="control-group">            <label class="control-label">联系人:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['Contact'];?>
</span>            </div>        </div>    </div>    <div class="span6">        <div class="control-group">            <label class="control-label">联系电话:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['Tel'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6">        <div class="control-group">            <label class="control-label">传真:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['Fax'];?>
</span>            </div>        </div>    </div>    <div class="span6">        <div class="control-group">            <label class="control-label">联系地址:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['Address'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">银行账户:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['BankAccount'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">银行户主:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['BankPeople'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">银行名称:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['BankName'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span12 ">        <div class="control-group">            <label class="control-label">备注:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['Notice'];?>
</span>            </div>        </div>    </div></div>    <h3 class="form-section"><?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['NameCn'];?>
文件信息：</h3>    <div class="row-fluid">        <div class="span12 ">            <div class="control-group">                <?php if ($_smarty_tpl->tpl_vars['travel_supplier_file']->value) {?>                <?php  $_smarty_tpl->tpl_vars['file'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['file']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['travel_supplier_file']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['file']->key => $_smarty_tpl->tpl_vars['file']->value) {
$_smarty_tpl->tpl_vars['file']->_loop = true;
?>                    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
<?php echo $_smarty_tpl->tpl_vars['file']->value['FileSrc'];?>
"><?php echo $_smarty_tpl->tpl_vars['file']->value['FileTitle'];?>
</a><br/>                <?php } ?>                <?php } else { ?>                暂无该旅游供应商的文件信息                <?php }?>            </div>        </div>    </div><div class="form-actions text-right">    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
TravelSupplier/EditTravelSupplier?travel_supplier_id=<?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['ID'];?>
"><button class="btn red"><i class="icon-pencil"></i>编辑旅游供应商</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
TravelSupplier/FileTravelSupplier?travel_supplier_id=<?php echo $_smarty_tpl->tpl_vars['travel_supplier']->value['ID'];?>
"><button class="btn blue"><i class="icon-pencil"></i>编辑文件</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
TravelSupplier/ListTravelSupplier"><button class="btn green">返回列表</button></a></div></div><!-- END FORM--></div></div></div><!-- END FOOTER --><!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) --><!-- BEGIN CORE PLUGINS --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-1.10.1.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script><!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/bootstrap.min.js" type="text/javascript"></script><!--[if lt IE 9]><script src="../../../../statics/resource/common/plugs/metronic/js/excanvas.min.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/respond.min.js"></script><![endif]--><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.slimscroll.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.blockui.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.cookie.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.uniform.min.js" type="text/javascript"></script><!-- END CORE PLUGINS --><!-- BEGIN PAGE LEVEL PLUGINS --><script type="text/javascript" src="../../../../statics/resource/common/plugs/metronic/js/select2.min.js"></script><!-- END PAGE LEVEL PLUGINS --><!-- BEGIN PAGE LEVEL SCRIPTS --><script src="../../../../statics/resource/common/plugs/metronic/js/app.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/form-samples.js"></script><!-- END PAGE LEVEL SCRIPTS --><script>    jQuery(document).ready(function () {        // initiate layout and plugins        App.init();        FormSamples.init();    });</script><!-- END JAVASCRIPTS --></body><!-- END BODY --></html><?php }} ?>
