<?php /* Smarty version Smarty-3.1.15, created on 2015-01-31 23:17:42
         compiled from "D:\wamp\www\iyouwu\themes\web\admin\goods_order\goods_order_view.html" */ ?>
<?php /*%%SmartyHeaderCode:1903654cce3742c9cf4-72919756%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '7d2d2a152135911fbd8caa42f9e528f05bb56cee' => 
    array (
      0 => 'D:\\wamp\\www\\iyouwu\\themes\\web\\admin\\goods_order\\goods_order_view.html',
      1 => 1422717460,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '1903654cce3742c9cf4-72919756',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.15',
  'unifunc' => 'content_54cce3744bdd71_53012488',
  'variables' => 
  array (
    'app_http_url' => 0,
    'goods_order' => 0,
    'order_goods' => 0,
    'goods' => 0,
    'goods_order_logs' => 0,
    'order_logs' => 0,
    'admin_account' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_54cce3744bdd71_53012488')) {function content_54cce3744bdd71_53012488($_smarty_tpl) {?><!DOCTYPE html><!--[if IE 8]><html lang="en" class="ie8"> <![endif]--><!--[if IE 9]><html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en"> <!--<![endif]--><!-- BEGIN HEAD --><head>    <meta charset="utf-8"/>    <title>尤物后台管理系统-订单信息</title>    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    <meta content="" name="description"/>    <meta content="" name="author"/>    <!-- BEGIN GLOBAL MANDATORY STYLES -->    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-metro.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-responsive.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/uniform.default.css" rel="stylesheet" type="text/css"/>    <!-- END GLOBAL MANDATORY STYLES -->    <!-- BEGIN PAGE LEVEL STYLES -->    <link rel="stylesheet" type="text/css" href="../../../../statics/resource/common/plugs/metronic/css/select2_metro.css"/>    <!-- END PAGE LEVEL SCRIPTS -->    <link rel="shortcut icon" href="../../../../statics/resource/common/plugs/metronic/image/favicon.ico"/></head><!-- END HEAD --><!-- BEGIN BODY --><body class="page-header-fixed" style="background-color:#FFFFFF !important"><div class="tab-pane margin-top-10"><div class="portlet box blue"><div class="portlet-title">    <div class="caption"><i class="icon-reorder"></i>查看订单信息</div>    <div class="tools">        <a href="javascript:;" class="collapse"></a>    </div></div><div class="portlet-body form"><!-- BEGIN FORM--><div class="form-horizontal form-view"><h3 class="form-section">    订单信息：    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsOrder/ListGoodsOrder"><button class="btn black" style="float: right">返回列表</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsOrder/EditGoodsOrder?goods_order_id=<?php echo $_smarty_tpl->tpl_vars['goods_order']->value['ID'];?>
"><button class="btn red" style="float: right"><i class="icon-pencil"></i>处理订单</button></a></h3><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">订单唯一编号:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['OrderSign'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">联系人:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['Contact'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">联系电话:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['Phone'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">邮箱:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['Email'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">运费:</label>            <div class="controls">                <span class="text">¥<?php echo $_smarty_tpl->tpl_vars['goods_order']->value['ExpressPrice'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">税费:</label>            <div class="controls">                <span class="text">¥<?php echo $_smarty_tpl->tpl_vars['goods_order']->value['TaxationPrice'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">其它费用:</label>            <div class="controls">                <span class="text">¥<?php echo $_smarty_tpl->tpl_vars['goods_order']->value['OtherPrice'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">总价:</label>            <div class="controls">                <span class="text">¥<?php echo $_smarty_tpl->tpl_vars['goods_order']->value['TotalPrice'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">订单来源:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['OrderSource'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">客人其它要求:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['OtherRequest'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">订单时间:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['CreateDate'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">下单IP:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['ClientOrderIp'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">支付状态:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods_order']->value['PayState']==0) {?>未支付<?php } else { ?>已支付<?php }?></span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">确认状态:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods_order']->value['ConfirmState']==0) {?>未状态<?php } else { ?>已状态<?php }?></span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">快递状态:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods_order']->value['ExpressState']==0) {?>未发货<?php } else { ?>已发货<?php }?></span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">邮寄店址:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['Address'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">总价包含:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['TotalPriceInclude'];?>
</span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">总价不包含:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['TotalPriceNotInclude'];?>
</span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span12">        <div class="control-group">            <label class="control-label">购买商品:</label>            <div class="controls">                <span class="text">                    <?php  $_smarty_tpl->tpl_vars['goods'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['goods']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['order_goods']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['goods']->key => $_smarty_tpl->tpl_vars['goods']->value) {
$_smarty_tpl->tpl_vars['goods']->_loop = true;
?>                        <a href="#?goods_id=<?php echo $_smarty_tpl->tpl_vars['goods']->value['Detail']['ID'];?>
"><?php echo $_smarty_tpl->tpl_vars['goods']->value['Detail']['NameCn'];?>
</a>，<?php echo $_smarty_tpl->tpl_vars['goods']->value['Num'];?>
个，单价¥<?php echo $_smarty_tpl->tpl_vars['goods']->value['UnionPrice'];?>
；                    <?php } ?>                </span>            </div>        </div>    </div></div><div class="row-fluid">    <div class="span6 ">        <div class="control-group">            <label class="control-label">是否有效:</label>            <div class="controls">                <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods_order']->value['Valid']==0) {?>无效<?php } else { ?>有效<?php }?></span>            </div>        </div>    </div>    <div class="span6 ">        <div class="control-group">            <label class="control-label">内部备注:</label>            <div class="controls">                <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_order']->value['InternalNotes'];?>
</span>            </div>        </div>    </div></div></div><!-- END FORM--></div></div><div class="portlet box blue"><div class="portlet-title">    <div class="caption"><i class="icon-reorder"></i>查看订单日志</div>    <div class="tools">        <a href="javascript:;" class="collapse"></a>    </div></div><div class="portlet-body form"><div class="form-horizontal form-view"><h3 class="form-section">订单日志：</h3>    <table class="table table-striped table-hover table-bordered" id="sample_editable_1">        <thead>        <tr>            <th width="10%">序号</th>            <th width="20%">时间</th>            <th width="10%">业务员</th>            <th width="30%">操作内容</th>            <th width="30%">内部备注</th>        </tr>        </thead>        <tbody>        <?php  $_smarty_tpl->tpl_vars['order_logs'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['order_logs']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['goods_order_logs']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['order_logs']->key => $_smarty_tpl->tpl_vars['order_logs']->value) {
$_smarty_tpl->tpl_vars['order_logs']->_loop = true;
?>        <tr>            <td width="10%" align="center"><?php echo $_smarty_tpl->tpl_vars['order_logs']->value['ID'];?>
</td>            <td width="20%" align="center"><?php echo $_smarty_tpl->tpl_vars['order_logs']->value['CreateDateTime'];?>
</td>            <td width="10%" align="center"><?php echo $_smarty_tpl->tpl_vars['admin_account']->value[$_smarty_tpl->tpl_vars['order_logs']->value['AdminAccountId']];?>
</td>            <td width="30%" align="center"><?php echo $_smarty_tpl->tpl_vars['order_logs']->value['OperationContent'];?>
</td>            <td width="30%" align="center"><?php echo $_smarty_tpl->tpl_vars['order_logs']->value['OrderNotice'];?>
</td>        </tr>        <?php } ?>        </tbody>    </table>    <div class="form-actions text-right">        <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsOrder/EditGoodsOrder?goods_order_id=<?php echo $_smarty_tpl->tpl_vars['goods_order']->value['ID'];?>
"><button class="btn red"><i class="icon-pencil"></i>编辑订单</button></a>        <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsOrder/ListGoodsOrder"><button class="btn black">返回列表</button></a>    </div></div></div></div></div><!-- END FOOTER --><!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) --><!-- BEGIN CORE PLUGINS --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-1.10.1.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script><!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/bootstrap.min.js" type="text/javascript"></script><!--[if lt IE 9]><script src="../../../../statics/resource/common/plugs/metronic/js/excanvas.min.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/respond.min.js"></script><![endif]--><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.slimscroll.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.blockui.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.cookie.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.uniform.min.js" type="text/javascript"></script><!-- END CORE PLUGINS --><!-- BEGIN PAGE LEVEL PLUGINS --><script type="text/javascript" src="../../../../statics/resource/common/plugs/metronic/js/select2.min.js"></script><!-- END PAGE LEVEL PLUGINS --><!-- BEGIN PAGE LEVEL SCRIPTS --><script src="../../../../statics/resource/common/plugs/metronic/js/app.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/form-samples.js"></script><!-- END PAGE LEVEL SCRIPTS --><script>    jQuery(document).ready(function () {        // initiate layout and plugins        App.init();        FormSamples.init();    });</script><!-- END JAVASCRIPTS --></body><!-- END BODY --></html><?php }} ?>
