<?php /* Smarty version Smarty-3.1.15, created on 2015-09-21 14:26:13
         compiled from "/data/home/byu17691/htdocs/themes/web/admin/goods_brand/goods_brand_view.html" */ ?>
<?php /*%%SmartyHeaderCode:195058998255ffa30593ba34-91633901%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '898aa280c33116c7cf477650df37c252031b7084' => 
    array (
      0 => '/data/home/byu17691/htdocs/themes/web/admin/goods_brand/goods_brand_view.html',
      1 => 1422375376,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '195058998255ffa30593ba34-91633901',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'goods_brand' => 0,
    'app_http_url' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.15',
  'unifunc' => 'content_55ffa3059b8ee3_84258229',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_55ffa3059b8ee3_84258229')) {function content_55ffa3059b8ee3_84258229($_smarty_tpl) {?><!DOCTYPE html><!--[if IE 8]><html lang="en" class="ie8"> <![endif]--><!--[if IE 9]><html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en"> <!--<![endif]--><!-- BEGIN HEAD --><head>    <meta charset="utf-8"/>    <title>尤物后台管理系统-品牌信息</title>    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    <meta content="" name="description"/>    <meta content="" name="author"/>    <!-- BEGIN GLOBAL MANDATORY STYLES -->    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-metro.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/style-responsive.css" rel="stylesheet" type="text/css"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>    <link href="../../../../statics/resource/common/plugs/metronic/css/uniform.default.css" rel="stylesheet" type="text/css"/>    <!-- END GLOBAL MANDATORY STYLES -->    <!-- BEGIN PAGE LEVEL STYLES -->    <link rel="stylesheet" type="text/css" href="../../../../statics/resource/common/plugs/metronic/css/select2_metro.css"/>    <!-- END PAGE LEVEL SCRIPTS -->    <link rel="shortcut icon" href="../../../../statics/resource/common/plugs/metronic/image/favicon.ico"/></head><!-- END HEAD --><!-- BEGIN BODY --><body class="page-header-fixed" style="background-color:#FFFFFF !important"><div class="tab-pane margin-top-10"><div class="portlet box blue"><div class="portlet-title">    <div class="caption"><i class="icon-reorder"></i><?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['NameCn'];?>
品牌信息查看</div>    <div class="tools">        <a href="javascript:;" class="collapse"></a>    </div></div><div class="portlet-body form"><!-- BEGIN FORM--><div class="form-horizontal form-view"><h3 class="form-section">    <?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['NameCn'];?>
基本信息：    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsBrand/ListGoodsBrand"><button class="btn green" style="float: right">返回列表</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsBrand/EditGoodsBrand?goods_brand_id=<?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['ID'];?>
"><button class="btn red" style="float: right"><i class="icon-pencil"></i>编辑品牌</button></a></h3>    <div class="row-fluid">        <div class="span4 ">            <div class="control-group">                <label class="control-label">中文名称:</label>                <div class="controls">                    <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['NameCn'];?>
</span>                </div>            </div>        </div>        <div class="span4">            <div class="control-group">                <label class="control-label">英文名称:</label>                <div class="controls">                    <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['NameEn'];?>
</span>                </div>            </div>        </div>        <div class="span4 ">            <div class="control-group">                <label class="control-label">是否有效:</label>                <div class="controls">                    <span class="text"><?php if ($_smarty_tpl->tpl_vars['goods_brand']->value['Valid']==1) {?>是<?php } else { ?>否<?php }?></span>                </div>            </div>        </div>    </div>    <div class="row-fluid">        <div class="span12">            <div class="control-group">                <label class="control-label">描述:</label>                <div class="controls">                    <span class="text"><?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['Introduction'];?>
</span>                </div>            </div>        </div>    </div>    <h3 class="form-section"><?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['NameCn'];?>
品牌图标：</h3>    <div class="row-fluid">        <div class="span12 ">            <div class="control-group">                <?php if ($_smarty_tpl->tpl_vars['goods_brand']->value['Logo']) {?>                <img src="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
<?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['Logo'];?>
" width="180" height="200">                <?php } else { ?>                暂无该线路的图片信息                <?php }?>            </div>        </div>    </div><div class="form-actions text-right">    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsBrand/EditGoodsBrand?goods_brand_id=<?php echo $_smarty_tpl->tpl_vars['goods_brand']->value['ID'];?>
"><button class="btn red"><i class="icon-pencil"></i>编辑品牌</button></a>    <a href="<?php echo $_smarty_tpl->tpl_vars['app_http_url']->value;?>
GoodsBrand/ListGoodsBrand"><button class="btn green">返回列表</button></a></div></div><!-- END FORM--></div></div></div><!-- END FOOTER --><!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) --><!-- BEGIN CORE PLUGINS --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-1.10.1.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script><!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip --><script src="../../../../statics/resource/common/plugs/metronic/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/bootstrap.min.js" type="text/javascript"></script><!--[if lt IE 9]><script src="../../../../statics/resource/common/plugs/metronic/js/excanvas.min.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/respond.min.js"></script><![endif]--><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.slimscroll.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.blockui.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.cookie.min.js" type="text/javascript"></script><script src="../../../../statics/resource/common/plugs/metronic/js/jquery.uniform.min.js" type="text/javascript"></script><!-- END CORE PLUGINS --><!-- BEGIN PAGE LEVEL PLUGINS --><script type="text/javascript" src="../../../../statics/resource/common/plugs/metronic/js/select2.min.js"></script><!-- END PAGE LEVEL PLUGINS --><!-- BEGIN PAGE LEVEL SCRIPTS --><script src="../../../../statics/resource/common/plugs/metronic/js/app.js"></script><script src="../../../../statics/resource/common/plugs/metronic/js/form-samples.js"></script><!-- END PAGE LEVEL SCRIPTS --><script>    jQuery(document).ready(function () {        // initiate layout and plugins        App.init();        FormSamples.init();    });</script><!-- END JAVASCRIPTS --></body><!-- END BODY --></html><?php }} ?>
